import {
  Music,
  Palette,
  Utensils,
  Laugh,
  Gift,
  Apple,
  Smartphone,
  Landmark,
  Trophy,
  BookOpen,
  HeartPulse,
  Laptop,
  Briefcase,
  Drama,
  Users,
  Wrench,
  Footprints,
  TreePine,
  Baby,
  Moon,
  ShoppingBag,
  Shirt,
  Camera,
  Gamepad2,
  MapPin,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  music: Music,
  art: Palette,
  'food & drink': Utensils,
  comedy: Laugh,
  free: Gift,
  'free food': Apple,
  influencers: Smartphone,
  heritage: Landmark,
  sports: Trophy,
  education: BookOpen,
  'health & wellness': HeartPulse,
  technology: Laptop,
  business: Briefcase,
  theater: Drama,
  broadway: Drama,
  entertainment: Sparkles,
  performance: Drama,
  community: Users,
  cultural: Landmark,
  networking: Users,
  workshop: Wrench,
  tour: Footprints,
  outdoor: TreePine,
  family: Baby,
  nightlife: Moon,
  shopping: ShoppingBag,
  fashion: Shirt,
  photography: Camera,
  gaming: Gamepad2,
  saved: HeartPulse,
  other: MapPin,
  all: Sparkles,
};

export function getCategoryIcon(category: string): LucideIcon {
  return ICON_MAP[category.toLowerCase()] || MapPin;
}

export const PRIMARY_CATEGORIES = [
  'all',
  'music',
  'food & drink',
  'comedy',
  'free',
  'nightlife',
] as const;

export const MORE_CATEGORIES = [
  'art',
  'sports',
  'education',
  'health & wellness',
  'technology',
  'theater',
  'outdoor',
  'other',
] as const;
